final Map<String, String> basicPhrasesMappings = {
  "Mga Ito": "LinguaAR/Dal/Basic Phrases/MgaIto",
  "Sila": "LinguaAR/Dal/Basic Phrases/Sila",
  "Ito": "LinguaAR/Dal/Basic Phrases/It",
  "Aking Sarili/Sarili ko": "LinguaAR/Dal/Basic Phrases/Myself",
  "Iyan": "LinguaAR/Dal/Basic Phrases/Iyan",
  "Ikaw": "LinguaAR/Dal/Basic Phrases/Ikaw",
  "Akin": "LinguaAR/Dal/Basic Phrases/Akin",
  "Mga Iyan": "LinguaAR/Dal/Basic Phrases/MgaIyan",
  "Siya (Lalaki)": "LinguaAR/Dal/Basic Phrases/He",
  "Atin": "LinguaAR/Dal/Basic Phrases/Atin",
  "Siya (Babae)": "LinguaAR/Dal/Basic Phrases/She",
  "Kanila": "LinguaAR/Dal/Basic Phrases/Kanila",
  "Sa Kanila": "LinguaAR/Dal/Basic Phrases/Them",
  "Kanya (Lalaki)": "LinguaAR/Dal/Basic Phrases/Him",
  "Sa Kanya (Lalaki)": "LinguaAR/Dal/Basic Phrases/His",
  "Tayo": "LinguaAR/Dal/Basic Phrases/Tayo",
  "Ako": "LinguaAR/Dal/Basic Phrases/Ako",
  "Sa Kanya (Babae)": "LinguaAR/Dal/Basic Phrases/Her",
  "Sayo": "LinguaAR/Dal/Basic Phrases/Sayo",
};
