final Map<String, String> familyFriendsMappings = {
  "Lola": "LinguaAR/Anthony/Pamilya/Lola",
  "Lolo": "LinguaAR/Anthony/Pamilya/Lolo",
  "Mama": "LinguaAR/Anthony/Pamilya/Mama",
  "Papa": "LinguaAR/Anthony/Pamilya/Papa",
  "Pamilya": "LinguaAR/Anthony/Pamilya/Pamilya",
  "Opo": "LinguaAR/Anthony/Pamilya/Opo",
  "Kuya": "LinguaAR/Anthony/Pamilya/Kuya",
  "Ate": "LinguaAR/Anthony/Pamilya/Ate",
  "Anak na lalaki (Son)": "LinguaAR/Anthony/Pamilya/Anak-na-lalaki",
  "Anak na babae (Daughter)": "LinguaAR/Anthony/Pamilya/Anak-na-babae",
  "Ninong": "LinguaAR/Anthony/Pamilya/Ninong",
  "Ninang": "LinguaAR/Anthony/Pamilya/Ninang",
  "Pinsan": "LinguaAR/Anthony/Pamilya/Pinsan",
  "Bata": "LinguaAR/Anthony/Pamilya/Bata",
  "Buntis": "LinguaAR/Anthony/Pamilya/Buntis",
  "Tinedyer": "LinguaAR/Anthony/Pamilya/Tinedyer",
  "Mga Bata": "LinguaAR/Anthony/Pamilya/Mga-Bata",
  "Tita": "LinguaAR/Anthony/Pamilya/Tita",
  "Tito": "LinguaAR/Anthony/Pamilya/Tito",
};
