final Map<String, String> fooddrinksMappings = {
  "Kape": "LinguaAR/Gulmatico/Foods/kape",
  "Cereal": "LinguaAR/Gulmatico/Foods/cereal",
  "Gutom": "LinguaAR/Gulmatico/Foods/gutom",
  "Hotdog": "LinguaAR/Gulmatico/Foods/hotdog",
  "Agahan": "LinguaAR/Gulmatico/Foods/agahan",
  "Tsaa": "LinguaAR/Gulmatico/Foods/tsaa",
  "Juice": "LinguaAR/Gulmatico/Foods/juice",
  "Itlog": "LinguaAR/Gulmatico/Foods/itlog",
  "Pancake": "LinguaAR/Gulmatico/Foods/pancake",
  "Ham": "LinguaAR/Gulmatico/Foods/ham",
  "Tinapay": "LinguaAR/Gulmatico/Foods/tinapay",
  "Inumin": "LinguaAR/Gulmatico/Foods/inumin",
  "Pagkain": "LinguaAR/Gulmatico/Foods/pagkain",
  "Soda": "LinguaAR/Gulmatico/Foods/soda",
  "Mantika": "LinguaAR/Gulmatico/Foods/mantika",
  "Tanghalian": "LinguaAR/Gulmatico/Foods/tanghalian",
  "Mayonnaise": "LinguaAR/Gulmatico/Foods/Mayonnaise",
  "Hapunan": "LinguaAR/Gulmatico/Foods/hapunan",
};
