final Map<String, String> pronounsMappings = {
  "Mga Ito": "LinguaAR/Dal/Pronouns/MgaIto",
  "Sila": "LinguaAR/Dal/Pronouns/Sila",
  "Ito": "LinguaAR/Dal/Pronouns/Ito",
  "Aking Sarili/Sarili ko": "LinguaAR/Dal/Pronouns/AkingSarili",
  "Iyan": "LinguaAR/Dal/Pronouns/Iyan",
  "Ikaw": "LinguaAR/Dal/Pronouns/Ikaw",
  "Akin": "LinguaAR/Dal/Pronouns/Akin",
  "Mga Iyan": "LinguaAR/Dal/Pronouns/MgaIyan",
  "Siya (Lalaki)": "LinguaAR/Dal/Pronouns/SiyaLalaki",
  "Atin": "LinguaAR/Dal/Pronouns/Atin",
  "Siya (Babae)": "LinguaAR/Dal/Pronouns/SiyaBabae",
  "Kanila": "LinguaAR/Dal/Pronouns/Kanila",
  "Sa Kanila": "LinguaAR/Dal/Pronouns/SaKanila",
  "Kanya (Lalaki)": "LinguaAR/Dal/Pronouns/KanyaLalaki",
  "Sa Kanya (Lalaki)": "LinguaAR/Dal/Pronouns/SaKanyaLalaki",
  "Tayo": "LinguaAR/Dal/Pronouns/Tayo",
  "Ako": "LinguaAR/Dal/Pronouns/Ako",
  "Sa Kanya (Babae)": "LinguaAR/Dal/Pronouns/SaKanyaBabae",
  "Sayo": "LinguaAR/Dal/Pronouns/Sayo",
};
