final Map<String, String> relationshipMappings = {
  "Valentines book": "LinguaAR/Anthony/Relasyon/Valentines-book",
  "Valentines card": "LinguaAR/Anthony/Relasyon/Valentines-card",
  "Valentines day": "LinguaAR/Anthony/Relasyon/Valentines-day",
  "Bulaklak": "LinguaAR/Anthony/Relasyon/Bulaklak",
  "Halik": "LinguaAR/Anthony/Relasyon/Halik",
  "Nobyo": "LinguaAR/Anthony/Relasyon/Nobyo",
  "Nobya": "LinguaAR/Anthony/Relasyon/Nobya",
  "Mahal kita": "LinguaAR/Anthony/Relasyon/Mahal-kita",
  "Mahal": "LinguaAR/Anthony/Relasyon/Mahal",
  "Gusto": "LinguaAR/Anthony/Relasyon/Gusto",
  "Yakap": "LinguaAR/Anthony/Relasyon/Yakap",
  "Paghanga": "LinguaAR/Anthony/Relasyon/Paghanga",
  "Gwapo": "LinguaAR/Anthony/Relasyon/Gwapo",
  "Maganda": "LinguaAR/Anthony/Relasyon/Maganda",
  "Naakit": "LinguaAR/Anthony/Relasyon/Naakit",
  "Lagi": "LinguaAR/Anthony/Relasyon/Lagi",
  "Kasal": "LinguaAR/Anthony/Relasyon/Kasal",
};
