final Map<String, List<String>> validWrongAnswers = {

  //Basic Phrases
  "Mga Ito": ["Mga Iyan", "Sila", "Ito"],
  "Sila": ["Mga Ito", "Mga Iyan", "Ito"],
  "Ito": ["Mga Ito", "Mga Iyan", "Sila"],
  "Aking Sarili/Sarili ko": ["Ikaw", "Akin", "Sayo"],
  "Iyan": ["Mga Ito", "Mga Iyan", "Sila"],
  "Ikaw": ["Ako", "Sayo", "Akin"],
  "Akin": ["Ikaw", "Sayo", "Ako"],
  "Mga Iyan": ["Mga Ito", "Sila", "Ito"],
  "Siya (Lalaki)": ["Siya (Babae)", "Sila", "Kanila"],
  "Atin": ["Akin", "Sayo", "Kanila"],
  "Siya (Babae)": ["Siya (Lalaki)", "Sila", "Kanila"],
  "Kanila": ["Atin", "Akin", "Sayo"],
  "Sa Kanila": ["Kanila", "Sila", "Sa Kanya (Lalaki)"],
  "Kanya (Lalaki)": ["Kanya (Babae)", "Sa Kanya (Lalaki)", "Kanila"],
  "Sa Kanya (Lalaki)": ["Sa Kanya (Babae)", "Kanya (Lalaki)", "Kanila"],
  "Tayo": ["Ako", "Ikaw", "Sila"],
  "Ako": ["Ikaw", "Sayo", "Akin"],
  "Sa Kanya (Babae)": ["Sa Kanya (Lalaki)", "Kanya (Babae)", "Kanila"],
  "Sayo": ["Ako", "Ikaw", "Akin"],


  // ===================== NEW: Daily Communication & Basic Phrases =====================
  // (These match your `basicPhrasesMappings` keys)
  "Magandang Gabi": ["Magandang Hapon", "Magandang Umaga",],
  "Magandang Hapon": ["Magandang Gabi", "Magandang Umaga",],
  "Magandang Umaga": ["Magandang Hapon", "Magandang Gabi",],
  "Tara Kain!": ["Magandang Hapon", "Paalam",],
  "Kumusta": ["Magandang Umaga", "Paalam"],
  "Anong Pangalan Mo?": ["Taga saan ka?", "Ilang taon ka na?"],
  "Matulog ka nang mahimbing": ["Magandang gabi", "Tara Kain!"],
  "Are you deaf?": ["Anong Pangalan Mo?", "Taga saan ka?"],

   // Family & Relationships
  "Lola": ["Lolo", "Mama", "Tita"],
  "Lolo": ["Lola", "Papa", "Tito"],
  "Mama": ["Papa", "Lola", "Tita"],
  "Papa": ["Mama", "Lolo", "Tito"],
  "Pamilya": ["Tita", "Tito", "Kuya"],
  "Opo": ["Hindi", "Salamat", "Walang anuman"],
  "Kuya": ["Ate", "Anak na lalaki (Son)", "Pinsan"],
  "Ate": ["Kuya", "Anak na babae (Daughter)", "Ninang"],
  "Anak na lalaki (Son)": ["Kuya", "Papa", "Tito"],
  "Anak na babae (Daughter)": ["Ate", "Mama", "Ninang"],
  "Ninong": ["Ninang", "Lolo", "Papa"],
  "Ninang": ["Ninong", "Lola", "Mama"],
  "Pinsan": ["Kuya", "Ate", "Bata"],
  "Bata": ["Tinedyer", "Mga Bata", "Anak na lalaki (Son)"],
  "Buntis": ["Bata", "Pamilya", "Mama"],
  "Tinedyer": ["Bata", "Kuya", "Ate"],
  "Mga Bata": ["Bata", "Anak na lalaki (Son)", "Anak na babae (Daughter)"],
  "Tita": ["Tito", "Mama", "Ninang"],
  "Tito": ["Tita", "Papa", "Ninong"],

  "Valentines book": ["Valentines card", "Halik", "Mahal"],
  "Valentines card": ["Valentines book", "Mahal kita", "Paghanga"],
  "Valentines day": ["Pasko", "Bagong Taon", "Kaarawan"],
  "Bulaklak": ["Regalo", "Halik", "Gusto"],
  "Halik": ["Yakap", "Mahal", "Gusto"],
  "Nobyo": ["Nobya", "Gusto", "Gwapo"],
  "Nobya": ["Nobyo", "Gusto", "Maganda"],
  "Mahal kita": ["Gusto", "Paghanga", "Naakit"],
  "Mahal": ["Gusto", "Naakit", "Gwapo"],
  "Gusto": ["Mahal kita", "Halik", "Lagi"],
  "Yakap": ["Halik", "Gusto", "Mahal"],
  "Paghanga": ["Mahal", "Gwapo", "Naakit"],
  "Gwapo": ["Maganda", "Paghanga", "Lagi"],
  "Maganda": ["Gwapo", "Gusto", "Naakit"],
  "Naakit": ["Paghanga", "Mahal kita", "Yakap"],
  "Lagi": ["Paghanga", "Mahal kita", "Naakit"],
  "Kasal": ["Mahal kita", "Pamilya", "Mahal"],



  // Work & Professions
  "Mananayaw": ["Singer", "Magsasaka", "Bumbero"],
  "Magsasaka": ["Karpentero", "Piloto", "Doctor"],
  "Karpentero": ["Magsasaka", "Electrician", "Pulis"],
  "Piloto": ["Doctor", "Bumbero", "Electrician"],
  "Electrician": ["Karpentero", "Doctor", "Nars"],
  "Nars": ["Doctor", "Dentista", "Pulis"],
  "Doctor": ["Dentista", "Nars", "Piloto"],
  "Dentista": ["Doctor", "Pulis", "Singer"],
  "Bumbero": ["Pulis", "Electrician", "Piloto"],
  "Singer": ["Mananayaw", "Dentista", "Nars"],
  "Pulis": ["Bumbero", "Electrician", "Karpentero"],

  // Technology
  "Computer": ["Laptop", "Telebisiyon", "Electric Fan"],
  "Telebisiyon": ["Computer", "Laptop", "Electric Fan"],
  "Mop": ["Electric Fan", "Computer", "Telebisiyon"],
  "Electric Fan": ["Mop", "Computer", "Laptop"],
  "Laptop": ["Computer", "Telebisiyon", "Electric Fan"],

  // Education
  "Krayola": ["Pambura", "Gunting", "Papel"],
  "Pambura": ["Krayola", "Lapis", "Gunting"],
  "Gunting": ["Krayola", "Pambura", "Lapis"],
  "Bag": ["Uniporme", "Papel", "Sapatos"],
  "Papel": ["Lapis", "Pambura", "Krayola"],
  "Sapatos": ["Bag", "Uniporme", "Itim na Sapatos"],
  "Uniporme": ["Bag", "Itim na Pisara", "Sapatos"],
  "Paaralan": ["Silid Aralan", "Itim na Pisara", "Upuan"],
  "Itim na Pisara": ["Paaralan", "Upuan", "Watawat"],
  "Upuan": ["Paaralan", "Silid Aralan", "Itim na Pisara"],
  "Watawat": ["Silid Aralan", "Paaralan", "Upuan"],
  "Silid Aralan": ["Paaralan", "Upuan", "Itim na Pisara"],
  "Itim na Sapatos": ["Sapatos", "Bag", "Uniporme"],
  "Lapis": ["Papel", "Krayola", "Pambura"],
 
  // Food & Drinks 
  "Kape": ["Tsaa", "Soda", "Mantika"],
  "Cereal": ["Pancake", "Itlog", "Hotdog"],
  "Gutom": ["Pagkain", "Tanghalian", "Hapunan"],
  "Hotdog": ["Ham", "Pancake", "Tinapay"],
  "Agahan": ["Tanghalian", "Hapunan", "Pagkain"],
  "Tsaa": ["Kape", "Juice", "Soda"],
  "Juice": ["Tsaa", "Inumin", "Soda"],
  "Itlog": ["Cereal", "Hotdog", "Tinapay"],
  "Pancake": ["Tinapay", "Itlog", "Ham"],
  "Ham": ["Hotdog", "Pancake", "Mayonnaise"],
  "Tinapay": ["Pancake", "Mantika", "Cereal"],
  "Inumin": ["Pagkain", "Mantika", "Mayonnaise"],
  "Pagkain": ["Gutom", "Tanghalian", "Inumin"],
  "Soda": ["Tsaa", "Juice", "Inumin"],
  "Mantika": ["Mayonnaise", "Pagkain", "Juice"],
  "Tanghalian": ["Agahan", "Hapunan", "Mantika"],
  "Mayonnaise": ["Mantika", "Juice", "Tinapay"],
  "Hapunan": ["Tanghalian", "Pagkain", "Agahan"],

  // Transportation 
  "Eroplano": ["Helicopter", "Hot air Balloon", "Paliparan"],
  "Helicopter": ["Eroplano", "Hot air Balloon", "Kalesa"],
  "Jeep": ["Bus", "Truck ng Basura", "Motorsiklo"],
  "Motorsiklo": ["Bisikleta", "Jeep", "Truck ng Bumbero"],
  "Truck ng Bumbero": ["Ambulansya", "Truck ng Basura", "Bus"],
  "Paliparan": ["Eroplano", "Hot air Balloon", "Kalesa"],
  "Kalesa": ["Bisikleta", "Motorsiklo", "Jeep"],
  "Bus": ["Jeep", "Truck ng Bumbero", "Ambulansya"],
  "Bisikleta": ["Motorsiklo", "Kalesa", "Jeep"],
  "Truck ng Basura": ["Truck ng Bumbero", "Ambulansya", "Motorsiklo"],
  "Ambulansya": ["Truck ng Bumbero", "Bus", "Hot air Balloon"],
  "Hot air Balloon": ["Eroplano", "Helicopter", "Paliparan"],

  // Emergency & Nature
  "Baha": ["Bagyo", "Ulan", "Lindol"],
  "Magnanakaw": ["Sunog", "Emergency", "Rescue"],
  "Sunog": ["Baha", "Bagyo", "Lindol"],
  "Tumawag ka ng tulong": ["Tulungan mo ako", "Tulungan mo sila", "Rescue"],
  "Rescue": ["Emergency", "Tumawag ka ng tulong", "Tulungan mo ako"],
  "Tulungan mo ako": ["Tumawag ka ng tulong", "Rescue", "Tulungan mo sila"],
  "Lindol": ["Baha", "Bagyo", "Ulan"],
  "Emergency": ["Rescue", "Sunog", "Tumawag ka ng tulong"],
  "Tulungan mo sila": ["Tulungan mo ako", "Rescue", "Tumawag ka ng tulong"],
  "Ulan": ["Bagyo", "Baha", "Lindol"],
  "Bagyo": ["Baha", "Lindol", "Ulan"],


  // Colors and shapes
  "Asul": ["Berde", "Kayumanggi", "Rosas"],
  "Itim": ["Abo", "Ginto", "Kahel"],
  "Kayumanggi": ["Abo", "Itim", "Kahel"],
  "Rosas": ["Kahel", "Asul", "Berde"],
  "Kahel": ["Rosas", "Ginto", "Berde"],
  "Abo": ["Itim", "Kayumanggi", "Ginto"],
  "Berde": ["Asul", "Kahel", "Rosas"],
  "Ginto": ["Abo", "Itim", "Kayumanggi"],
  "Paresukat": ["Bilog", "Abo", "Kayumanggi"], 
  "Bilog": ["Paresukat", "Kahel", "Berde"], 
  // ===================== NEW: Alphabet and Numbers Wrong Answers =====================
  "A": ["B", "C"],
  "B": ["A", "D"],
  "C": ["A", "E"],
  "D": ["B", "F"],
  "E": ["C", "G"],
  "F": ["D", "H"],
  "G": ["E", "I"],
  "H": ["F", "J"],
  "I": ["G", "K"],
  "J": ["H", "L"],
  "K": ["I", "M"],
  "L": ["J", "N"],
  "M": ["K", "O"],
  "N": ["L", "P"],
  "O": ["M", "Q"],
  "P": ["N", "R"],
  "Q": ["O", "S"],
  "R": ["P", "T"],
  "S": ["Q", "U"],
  "T": ["R", "V"],
  "U": ["S", "W"],
  "V": ["T", "X"],
  "W": ["U", "Y"],
  "X": ["V", "Z"],
  "Y": ["W", "Z"],
  "Z": ["X", "Y"],

  "Isa": ["Dalawa", "Tatlo"],
  "Dalawa": ["Isa", "Apat"],
  "Tatlo": ["Dalawa", "Lima"],
  "Apat": ["Tatlo", "Lima"],
  "Lima": ["Apat", "Anim"],
  "Anim": ["Lima", "Pito"],
  "Pito": ["Anim", "Walo"],
  "Walo": ["Pito", "Siyam"],
  "Siyam": ["Walo", "Sampu"],
  "Sampu": ["Siyam", "Isa"],


};


