final Map<String, List<String>> validWrongAnswers = {
  "Mga Ito": ["Mga Iyan", "Sila", "Ito"],
  "Sila": ["Mga Ito", "Mga Iyan", "Ito"],
  "Ito": ["Mga Ito", "Mga Iyan", "Sila"],
  "Aking Sarili/Sarili ko": ["Ikaw", "Akin", "Sayo"],
  "Iyan": ["Mga Ito", "Mga Iyan", "Sila"],
  "Ikaw": ["Ako", "Sayo", "Akin"],
  "Akin": ["Ikaw", "Sayo", "Ako"],
  "Mga Iyan": ["Mga Ito", "Sila", "Ito"],
  "Siya (Lalaki)": ["Siya (Babae)", "Sila", "Kanila"],
  "Atin": ["Akin", "Sayo", "Kanila"],
  "Siya (Babae)": ["Siya (Lalaki)", "Sila", "Kanila"],
  "Kanila": ["Atin", "Akin", "Sayo"],
  "Sa Kanila": ["Kanila", "Sila", "Sa Kanya (Lalaki)"],
  "Kanya (Lalaki)": ["Kanya (Babae)", "Sa Kanya (Lalaki)", "Kanila"],
  "Sa Kanya (Lalaki)": ["Sa Kanya (Babae)", "Kanya (Lalaki)", "Kanila"],
  "Tayo": ["Ako", "Ikaw", "Sila"],
  "Ako": ["Ikaw", "Sayo", "Akin"],
  "Sa Kanya (Babae)": ["Sa Kanya (Lalaki)", "Kanya (Babae)", "Kanila"],
  "Sayo": ["Ako", "Ikaw", "Akin"],
};